@ECHO OFF

SET SPELLCHECK_SERVICE_NAME=ASC Spellcheck Server
SET INSTAL_SERVICE_FOLDER=Common
SET INSTAL_SCRIPT_FOLDER=install
SET SERVICE_FOLDER=SpellChecker

call %~dp0\%SERVICE_FOLDER%\%INSTAL_SCRIPT_FOLDER%\InstallNodeJSSpellCheck.bat
@IF NOT "%ERRORLEVEL%"=="0" goto ERROR

call %~dp0\%INSTAL_SERVICE_FOLDER%\%INSTAL_SCRIPT_FOLDER%\InstallAndRunService.bat "%SPELLCHECK_SERVICE_NAME%" "node.exe %~dp0\%SERVICE_FOLDER%\sources\server.js"
@IF NOT "%ERRORLEVEL%"=="0" goto ERROR


:ERROR
:SUCCESS
pause

exit /b 0